version: '3.8'

services:
  frontend:
    build: ./example-frontend
    ports:
      - 5000:5000  
  backend:
    build: ./example-backend
    ports:
      - 8080:8080
    environment: 
      - REDIS_HOST=redis
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
  redis:
    image: redis:6.2.6
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres