version: '3.8'

services:
  nginx:
    image: nginx:1.21
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  frontend:
    build: ./example-frontend  
  backend:
    build: ./example-backend
    environment: 
      - REDIS_HOST=redis
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
  redis:
    image: redis:6.2.6
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres