version: '3.8'

services:
  frontend:
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000
  backend:
    build: ./ml-kurkkumopo-backend
    depends_on:
        - training
    volumes:
      - model:/src/model
    ports:
      - 5000:5000
  training:
    build: ./ml-kurkkumopo-training
    volumes:
      - ./ml-kurkkumopo-training/images:/src/imgs
      - ./ml-kurkkumopo-training/data:/src/data
      - model:/src/model

volumes:
  model: